export const SEED_PACKAGES = [
  {
    id: 'gorgeous-georgia',
    destination: 'Gorgeous Georgia',
    badge: 'Caucasus Charm',
    badgeColor: '#7e5233',
    category: 'group',
    duration: '5 Days & 4 Nights',
    title: 'Gorgeous Georgia',
    subtitle: 'Tbilisi & Beyond',
    hotels: '4N Premium Hotel in Tbilisi',
    originalPrice: 28000,
    salePrice: 23999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1565018042456-075e7a9b0c51?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1565018042456-075e7a9b0c51?w=1400&q=85',
    itineraryPdf: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    overview: 'Experience the magic of Georgia with its ancient churches, stunning mountains, and renowned wine culture. Explore the cobbled streets of Tbilisi and the majestic Caucasus.',
    highlights: ['Tbilisi City Tour', 'Kazbegi Mountain Excursion', 'Mtskheta Ancient Capital', 'Georgian Wine Tasting'],
    inclusions: ['4 nights accommodation', 'Daily breakfast', 'Airport transfers', 'Guided sightseeing'],
    exclusions: ['Flights', 'Visa fees', 'Lunches & Dinners', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Arrival in Tbilisi', description: 'Arrive at Tbilisi International Airport, transfer to hotel and relax.', activities: ['Transfer', 'Check-in'] },
      { day: 2, title: 'Tbilisi City Tour', description: 'Explore the old town, Narikala Fortress, and Sulfur Baths.', activities: ['Cable Car', 'Old Town Walk'] },
      { day: 3, title: 'Kazbegi Excursion', description: 'Drive along the Georgian Military Highway to Kazbegi.', activities: ['Gergeti Trinity Church', 'Scenic Drive'] },
      { day: 4, title: 'Mtskheta & Wine Route', description: 'Visit the ancient capital and enjoy traditional wine tasting.', activities: ['Jvari Monastery', 'Wine Tasting'] },
      { day: 5, title: 'Departure', description: 'Transfer to the airport for your flight back home.', activities: ['Checkout', 'Departure'] }
    ]
  },
  {
    id: 'awesome-azerbaijan',
    destination: 'Awesome Azerbaijan',
    badge: 'Land of Fire',
    badgeColor: '#2e9e7a',
    category: 'group',
    duration: '4 Days & 3 Nights',
    title: 'Awesome Azerbaijan',
    subtitle: 'Baku & Absheron Peninsula',
    hotels: '3N Luxury Hotel in Baku',
    originalPrice: 26000,
    salePrice: 21999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1582236378413-ebbd161ef9cf?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1582236378413-ebbd161ef9cf?w=1400&q=85',
    itineraryPdf: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    overview: 'Discover the contrast between the ancient walled city of Baku and its futuristic Flame Towers. Witness the natural burning fires of the Absheron Peninsula.',
    highlights: ['Baku Old City (Icherisheher)', 'Flame Towers', 'Yanar Dag (Burning Mountain)', 'Heydar Aliyev Center'],
    inclusions: ['3 nights accommodation', 'Breakfast', 'Airport transfers', 'Absheron Tour'],
    exclusions: ['Flights', 'Visa', 'Meals not mentioned', 'Entrance fees'],
    itinerary: [
      { day: 1, title: 'Baku Arrival', description: 'Arrive in Baku and transfer to your hotel. Evening stroll at Baku Boulevard.', activities: ['Check-in', 'Boulevard Walk'] },
      { day: 2, title: 'Baku City Tour', description: 'Explore the Old City, Maiden Tower, and Shirvanshahs Palace.', activities: ['Old City', 'Flame Towers Photo Stop'] },
      { day: 3, title: 'Absheron Peninsula', description: 'Visit the Ateshgah Fire Temple and the burning mountain of Yanar Dag.', activities: ['Fire Temple', 'Yanar Dag'] },
      { day: 4, title: 'Departure', description: 'Morning shopping at local bazaars, then transfer to airport.', activities: ['Shopping', 'Departure'] }
    ]
  },
  {
    id: 'crazy-thailand',
    destination: 'Crazy Thailand',
    badge: 'Tropical Vibes',
    badgeColor: '#0ea5e9',
    category: 'group',
    duration: '5 Days & 4 Nights',
    title: 'Crazy Thailand',
    subtitle: 'Phuket & Krabi',
    hotels: '2N Krabi · 2N Phuket',
    originalPrice: 32000,
    salePrice: 26999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1400&q=85',
    itineraryPdf: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    overview: 'Unwind on the pristine beaches of Krabi and experience the vibrant nightlife of Phuket. The perfect tropical getaway.',
    highlights: ['Phi Phi Island Tour', '4 Islands Tour in Krabi', 'Patong Beach Nightlife', 'Big Buddha'],
    inclusions: ['4 nights stay', 'Daily breakfast', 'Island Tours with Lunch', 'Inter-city transfers'],
    exclusions: ['Flights', 'National Park Fees', 'Dinner', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Arrival in Krabi', description: 'Arrive in Krabi and relax at Ao Nang beach.', activities: ['Check-in', 'Beach Leisure'] },
      { day: 2, title: 'Krabi 4 Islands Tour', description: 'Speedboat tour to Phra Nang Cave, Tup Island, Chicken Island, and Poda Island.', activities: ['Snorkeling', 'Island Hopping'] },
      { day: 3, title: 'Krabi to Phuket', description: 'Transfer to Phuket. Evening explore Bangla Road.', activities: ['Transfer', 'Nightlife'] },
      { day: 4, title: 'Phi Phi Island Tour', description: 'Full day excursion to the beautiful Phi Phi Islands.', activities: ['Speedboat', 'Maya Bay View', 'Snorkeling'] },
      { day: 5, title: 'Departure', description: 'Transfer to Phuket airport.', activities: ['Checkout', 'Departure'] }
    ]
  },
  {
    id: 'aspiring-almaty',
    destination: 'Aspiring Almaty',
    badge: 'Mountain City',
    badgeColor: '#e8520a',
    category: 'group',
    duration: '4 Days & 3 Nights',
    title: 'Aspiring Almaty',
    subtitle: 'Nature & Modernity',
    hotels: '3N Premium Hotel in Almaty',
    originalPrice: 30000,
    salePrice: 24999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1588636184511-9252c80c2f32?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1588636184511-9252c80c2f32?w=1400&q=85',
    itineraryPdf: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    overview: 'Experience the largest city of Kazakhstan, set beautifully against the backdrop of the Trans-Ili Alatau mountains.',
    highlights: ['Shymbulak Ski Resort', 'Medeu Ice Rink', 'Kok Tobe Hill', 'Zenkov Cathedral'],
    inclusions: ['3 nights accommodation', 'Breakfast', 'Cable car tickets', 'City Tour'],
    exclusions: ['Flights', 'Skiing equipment', 'Meals', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Almaty Arrival', description: 'Transfer to hotel. Evening visit to Panfilov Park.', activities: ['Check-in', 'Park Stroll'] },
      { day: 2, title: 'Kok Tobe & City Tour', description: 'Cable car ride to Kok Tobe for panoramic views of the city.', activities: ['Cable Car', 'City Views'] },
      { day: 3, title: 'Medeu & Shymbulak', description: 'Visit the highest skating rink in the world and ride up to Shymbulak.', activities: ['Mountain Views', 'Ski Resort'] },
      { day: 4, title: 'Departure', description: 'Shopping at Green Bazaar and departure.', activities: ['Green Bazaar', 'Departure'] }
    ]
  },
  {
    id: 'unique-uzbek',
    destination: 'Unique Uzbek',
    badge: 'Silk Road',
    badgeColor: '#153e2d',
    category: 'group',
    duration: '6 Days & 5 Nights',
    title: 'Unique Uzbek',
    subtitle: 'Tashkent, Samarkand & Bukhara',
    hotels: '2N Tashkent · 2N Samarkand · 1N Bukhara',
    originalPrice: 42000,
    salePrice: 37999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1627056086811-09be353e8964?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1627056086811-09be353e8964?w=1400&q=85',
    itineraryPdf: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    overview: 'Step back in time and travel the ancient Silk Road. Marvel at the stunning blue-tiled architecture of Samarkand and the historic center of Bukhara.',
    highlights: ['Registan Square', 'Afrosiyab Bullet Train', 'Bukhara Old City', 'Tashkent Metro'],
    inclusions: ['5 nights accommodation', 'Breakfast', 'Bullet train tickets', 'Guided tours'],
    exclusions: ['Flights', 'Visa', 'Lunches & Dinners', 'Photo fees at monuments'],
    itinerary: [
      { day: 1, title: 'Arrival in Tashkent', description: 'Welcome to Uzbekistan! City tour including Independence Square.', activities: ['City Tour', 'Tashkent Metro'] },
      { day: 2, title: 'Tashkent to Samarkand', description: 'Take the Afrosiyab train to Samarkand. Visit Gur-e-Amir.', activities: ['Train Ride', 'Mausoleum'] },
      { day: 3, title: 'Samarkand Highlights', description: 'Explore the majestic Registan Square and Bibi-Khanym Mosque.', activities: ['Registan', 'Shah-i-Zinda'] },
      { day: 4, title: 'Samarkand to Bukhara', description: 'Transfer to Bukhara. Evening walk in the Old City.', activities: ['Scenic Drive', 'Old City Walk'] },
      { day: 5, title: 'Bukhara Exploration', description: 'Full day tour of Bukhara including Po-i-Kalyan complex.', activities: ['Kalyan Minaret', 'Trading Domes'] },
      { day: 6, title: 'Departure', description: 'Flight back from Bukhara or train to Tashkent for departure.', activities: ['Checkout', 'Departure'] }
    ]
  },
  {
    id: 'shining-srilanka',
    destination: 'Shining Srilanka',
    badge: 'Tropical Heritage',
    badgeColor: '#7e5233',
    category: 'group',
    duration: '5 Days & 4 Nights',
    title: 'Shining Srilanka',
    subtitle: 'Kandy, Nuwara Eliya & Bentota',
    hotels: '1N Kandy · 1N Nuwara Eliya · 2N Bentota',
    originalPrice: 35000,
    salePrice: 29999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1585394365777-e81a5f5bf68a?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1585394365777-e81a5f5bf68a?w=1400&q=85',
    itineraryPdf: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    overview: 'Experience the teardrop of India. From the sacred Temple of the Tooth to lush tea estates and golden sandy beaches.',
    highlights: ['Temple of the Sacred Tooth Relic', 'Tea Plantations', 'Madu River Safari', 'Bentota Beaches'],
    inclusions: ['4 nights stay', 'Daily Breakfast', 'Private AC car with English speaking driver', 'Madu River Safari'],
    exclusions: ['Flights', 'Visa (ETA)', 'Entrance Fees', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Colombo to Kandy', description: 'Arrive in Colombo, transfer to Kandy. Visit Pinnawala Elephant Orphanage en route.', activities: ['Pinnawala', 'Temple of Tooth'] },
      { day: 2, title: 'Kandy to Nuwara Eliya', description: 'Drive through beautiful tea gardens to "Little England".', activities: ['Tea Factory Tour', 'Gregory Lake'] },
      { day: 3, title: 'Nuwara Eliya to Bentota', description: 'Travel down to the coastal town of Bentota.', activities: ['Scenic Drive', 'Beach Leisure'] },
      { day: 4, title: 'Bentota Sightseeing', description: 'Enjoy a boat ride on the Madu River and visit a turtle hatchery.', activities: ['River Safari', 'Turtle Hatchery'] },
      { day: 5, title: 'Departure', description: 'Transfer to Colombo airport for departure.', activities: ['Colombo City Tour', 'Departure'] }
    ]
  },
  {
    id: 'marvellous-malaysia',
    destination: 'Marvellous Malaysia',
    badge: 'Truly Asia',
    badgeColor: '#2e3da8',
    category: 'group',
    duration: '5 Days & 4 Nights',
    title: 'Marvellous Malaysia',
    subtitle: 'Kuala Lumpur & Genting Highlands',
    hotels: '3N Kuala Lumpur · 1N Genting',
    originalPrice: 36000,
    salePrice: 31999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=1400&q=85',
    itineraryPdf: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    overview: 'Discover a melting pot of cultures, ultra-modern skyscrapers, and cool highland resorts in Malaysia.',
    highlights: ['Petronas Twin Towers', 'Batu Caves', 'Awana SkyWay Cable Car', 'Genting Highlands Theme Park'],
    inclusions: ['4 nights accommodation', 'Daily breakfast', 'Cable car tickets', 'City Tour'],
    exclusions: ['Flights', 'Tourism Tax', 'Lunches & Dinners', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Arrival in Kuala Lumpur', description: 'Transfer to hotel and relax. Evening explore Bukit Bintang.', activities: ['Check-in', 'Shopping'] },
      { day: 2, title: 'Kuala Lumpur City Tour', description: 'Half day city tour including KL Tower and Petronas Twin Towers photo stop.', activities: ['City Tour', 'KL Tower'] },
      { day: 3, title: 'Batu Caves & Genting', description: 'Visit Batu Caves before heading up to Genting Highlands via cable car.', activities: ['Batu Caves', 'Cable Car Ride'] },
      { day: 4, title: 'Genting Highlands', description: 'Full day enjoying the cool climate and theme parks.', activities: ['Theme Park', 'Casino De Genting'] },
      { day: 5, title: 'Departure', description: 'Transfer back to KLIA for your flight home.', activities: ['Checkout', 'Departure'] }
    ]
  },
  {
    id: 'rising-russia',
    destination: 'Rising Russia',
    badge: 'Imperial Grandeur',
    badgeColor: '#c92a2a',
    category: 'group',
    duration: '7 Days & 6 Nights',
    title: 'Rising Russia',
    subtitle: 'Moscow & St. Petersburg',
    hotels: '3N Moscow · 3N St. Petersburg',
    originalPrice: 65000,
    salePrice: 58999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1547448415-e9f5b28e570d?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1547448415-e9f5b28e570d?w=1400&q=85',
    itineraryPdf: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    overview: 'Experience the grandeur of the Tsars. Explore the iconic Red Square in Moscow and the magnificent palaces of St. Petersburg.',
    highlights: ['Red Square & Kremlin', 'St. Basil\'s Cathedral', 'Hermitage Museum', 'Sapsan High-Speed Train'],
    inclusions: ['6 nights stay', 'Breakfast', 'Sapsan train tickets', 'Guided tours'],
    exclusions: ['Flights', 'Visa fees', 'Entrance fees to museums', 'Meals'],
    itinerary: [
      { day: 1, title: 'Arrival in Moscow', description: 'Transfer to hotel. Evening walk down Arbat Street.', activities: ['Check-in', 'Arbat Street'] },
      { day: 2, title: 'Moscow City Tour', description: 'Visit Red Square, St. Basil\'s, and the Moscow Metro.', activities: ['Red Square', 'Metro Tour'] },
      { day: 3, title: 'The Kremlin', description: 'Guided tour of the Kremlin grounds and cathedrals.', activities: ['Kremlin', 'Armoury Chamber'] },
      { day: 4, title: 'Moscow to St. Petersburg', description: 'Take the Sapsan train to St. Petersburg.', activities: ['Sapsan Train', 'Nevsky Prospect'] },
      { day: 5, title: 'Hermitage Museum', description: 'Full day exploring the world-famous Hermitage Museum.', activities: ['Hermitage', 'Palace Square'] },
      { day: 6, title: 'Peterhof Palace', description: 'Visit the "Russian Versailles" known for its spectacular fountains.', activities: ['Peterhof', 'Fountain Park'] },
      { day: 7, title: 'Departure', description: 'Transfer to airport for departure.', activities: ['Checkout', 'Departure'] }
    ]
  },
  {
    id: 'vibrant-vietnam',
    destination: 'Vibrant Vietnam',
    badge: 'Cultural Wonders',
    badgeColor: '#153e2d',
    category: 'group',
    duration: '6 Days & 5 Nights',
    title: 'Vibrant Vietnam',
    subtitle: 'Hanoi & Halong Bay',
    hotels: '3N Hanoi · 1N Halong Bay Cruise · 1N Ninh Binh',
    originalPrice: 40000,
    salePrice: 35999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=1400&q=85',
    itineraryPdf: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    overview: 'Discover the rich history of Hanoi, cruise through the emerald waters of Halong Bay, and explore the breathtaking landscapes of Ninh Binh.',
    highlights: ['Halong Bay Overnight Cruise', 'Hanoi Old Quarter', 'Trang An Boat Ride', 'Water Puppet Show'],
    inclusions: ['5 nights accommodation', 'All meals on Halong cruise', 'Transfers', 'English speaking guide'],
    exclusions: ['Flights', 'Visa stamping fee', 'Other meals', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Hanoi Arrival', description: 'Arrive in Hanoi. Evening Water Puppet Show.', activities: ['Check-in', 'Water Puppet Show'] },
      { day: 2, title: 'Hanoi City Tour', description: 'Visit Ho Chi Minh Mausoleum and Temple of Literature.', activities: ['City Tour', 'Old Quarter Rickshaw'] },
      { day: 3, title: 'Hanoi to Halong Bay', description: 'Transfer to Halong Bay. Board your cruise for an overnight stay.', activities: ['Cruise Boarding', 'Cave Exploration', 'Seafood Dinner'] },
      { day: 4, title: 'Halong to Ninh Binh', description: 'Morning Tai Chi. Disembark and drive to Ninh Binh.', activities: ['Tai Chi', 'Scenic Drive'] },
      { day: 5, title: 'Ninh Binh Exploration', description: 'Boat ride in Trang An (Halong on land). Return to Hanoi.', activities: ['Trang An Boat Ride', 'Mua Cave'] },
      { day: 6, title: 'Departure', description: 'Transfer to Noi Bai airport for departure.', activities: ['Checkout', 'Departure'] }
    ]
  },
  {
    id: 'trending-turkey',
    destination: 'Trending Turkey',
    badge: 'East Meets West',
    badgeColor: '#e8520a',
    category: 'group',
    duration: '7 Days & 6 Nights',
    title: 'Trending Turkey',
    subtitle: 'Istanbul & Cappadocia',
    hotels: '3N Istanbul · 3N Cappadocia',
    originalPrice: 55000,
    salePrice: 49999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=1400&q=85',
    itineraryPdf: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    overview: 'Experience the magic of Turkey. From the bustling bazaars and grand mosques of Istanbul to the surreal fairy chimneys of Cappadocia.',
    highlights: ['Hot Air Balloon Ride (Optional)', 'Blue Mosque & Hagia Sophia', 'Bosphorus Cruise', 'Goreme Open Air Museum'],
    inclusions: ['6 nights stay', 'Daily Breakfast', 'Domestic flights (IST-ASR)', 'Guided Tours'],
    exclusions: ['International Flights', 'Hot Air Balloon Ride', 'Visa', 'Entrance Fees'],
    itinerary: [
      { day: 1, title: 'Arrival in Istanbul', description: 'Transfer to hotel. Evening free to explore Taksim Square.', activities: ['Check-in', 'Taksim Square'] },
      { day: 2, title: 'Istanbul Old City Tour', description: 'Visit Blue Mosque, Hagia Sophia, and Topkapi Palace.', activities: ['Historical Tour', 'Grand Bazaar'] },
      { day: 3, title: 'Bosphorus Cruise', description: 'Cruise between Europe and Asia. Afternoon flight to Cappadocia.', activities: ['Bosphorus Cruise', 'Domestic Flight'] },
      { day: 4, title: 'Cappadocia North Tour', description: 'Visit Goreme Open Air Museum and fairy chimneys.', activities: ['Goreme', 'Pottery Workshop'] },
      { day: 5, title: 'Cappadocia South Tour', description: 'Explore Underground City and Ihlara Valley.', activities: ['Underground City', 'Valley Hike'] },
      { day: 6, title: 'Return to Istanbul', description: 'Morning optional Hot Air Balloon. Fly back to Istanbul.', activities: ['Balloon Ride', 'Flight to IST'] },
      { day: 7, title: 'Departure', description: 'Transfer to airport for your journey home.', activities: ['Checkout', 'Departure'] }
    ]
  },
  {
    id: 'tulips-to-eiffel',
    destination: 'Tulips to Eiffel',
    badge: 'Classic Europe',
    badgeColor: '#2e9e7a',
    category: 'group',
    duration: '8 Days & 7 Nights',
    title: 'Tulips to Eiffel',
    subtitle: 'Amsterdam, Brussels & Paris',
    hotels: '2N Amsterdam · 2N Brussels · 3N Paris',
    originalPrice: 110000,
    salePrice: 95000,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1502602898657-3e907600bb43?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1502602898657-3e907600bb43?w=1400&q=85',
    itineraryPdf: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    overview: 'A magical journey through Western Europe. See the canals of Amsterdam, the chocolates of Brussels, and the romance of Paris.',
    highlights: ['Keukenhof / Zaanse Schans', 'Eiffel Tower 2nd Level', 'Seine River Cruise', 'Atomium Brussels'],
    inclusions: ['7 nights accommodation', 'Daily Breakfast', 'Inter-city train tickets', 'Key Attraction Tickets'],
    exclusions: ['Flights', 'Schengen Visa', 'City Taxes', 'Lunches & Dinners'],
    itinerary: [
      { day: 1, title: 'Amsterdam Arrival', description: 'Arrive in Amsterdam. Evening Canal Cruise.', activities: ['Check-in', 'Canal Cruise'] },
      { day: 2, title: 'Dutch Countryside', description: 'Visit windmills in Zaanse Schans and a cheese factory.', activities: ['Windmills', 'Cheese Tasting'] },
      { day: 3, title: 'Amsterdam to Brussels', description: 'Take the train to Brussels. Visit the Grand Place.', activities: ['Train Ride', 'Grand Place'] },
      { day: 4, title: 'Brussels Tour', description: 'Visit Atomium and enjoy Belgian chocolates and waffles.', activities: ['Atomium', 'Chocolate Tour'] },
      { day: 5, title: 'Brussels to Paris', description: 'Train to Paris. Evening Seine River Cruise.', activities: ['Train Ride', 'Seine Cruise'] },
      { day: 6, title: 'Paris City Tour', description: 'Visit Eiffel Tower, Arc de Triomphe, and Champs-Élysées.', activities: ['Eiffel Tower', 'City Tour'] },
      { day: 7, title: 'Disneyland or Louvre', description: 'Free day. Choose to visit Disneyland Paris or the Louvre.', activities: ['Optional Tour'] },
      { day: 8, title: 'Departure', description: 'Transfer to CDG airport.', activities: ['Checkout', 'Departure'] }
    ]
  },
  {
    id: 'jazzy-japan',
    destination: 'Jazzy Japan',
    badge: 'Modern & Traditional',
    badgeColor: '#0ea5e9',
    category: 'group',
    duration: '7 Days & 6 Nights',
    title: 'Jazzy Japan',
    subtitle: 'Tokyo, Kyoto & Osaka',
    hotels: '3N Tokyo · 2N Kyoto · 1N Osaka',
    originalPrice: 130000,
    salePrice: 115000,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1400&q=85',
    itineraryPdf: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    overview: 'Experience the beautiful contrast of Japan, from the neon-lit streets of Tokyo to the tranquil temples of Kyoto.',
    highlights: ['Shinkansen (Bullet Train) Ride', 'Mt. Fuji & Hakone Tour', 'Fushimi Inari Shrine', 'Osaka Castle'],
    inclusions: ['6 nights accommodation', 'Daily Breakfast', 'JR Pass (7 Days)', 'Mt. Fuji Excursion'],
    exclusions: ['Flights', 'Visa', 'Lunches & Dinners', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Tokyo Arrival', description: 'Arrive at Narita/Haneda. Transfer to hotel.', activities: ['Check-in', 'Rest'] },
      { day: 2, title: 'Tokyo City Tour', description: 'Visit Senso-ji Temple, Shibuya Crossing, and Tokyo Tower.', activities: ['Senso-ji', 'Shibuya'] },
      { day: 3, title: 'Mt. Fuji Excursion', description: 'Full day tour to Mt. Fuji 5th station and Lake Ashi cruise.', activities: ['Mt. Fuji', 'Hakone Cruise'] },
      { day: 4, title: 'Tokyo to Kyoto', description: 'Take the Bullet Train to Kyoto. Visit Kinkaku-ji (Golden Pavilion).', activities: ['Bullet Train', 'Golden Pavilion'] },
      { day: 5, title: 'Kyoto Heritage', description: 'Explore Fushimi Inari Shrine and Arashiyama Bamboo Forest.', activities: ['Fushimi Inari', 'Bamboo Grove'] },
      { day: 6, title: 'Kyoto to Osaka', description: 'Short train ride to Osaka. Visit Osaka Castle and Dotonbori.', activities: ['Osaka Castle', 'Dotonbori Street Food'] },
      { day: 7, title: 'Departure', description: 'Transfer to Kansai airport.', activities: ['Checkout', 'Departure'] }
    ]
  },
  {
    id: 'european-delights',
    destination: 'European Delights',
    badge: 'Grand Tour',
    badgeColor: '#7e5233',
    category: 'group',
    duration: '10 Days & 9 Nights',
    title: 'European Delights',
    subtitle: 'Switzerland, Italy & France',
    hotels: '3N Swiss Alps · 3N Italy · 3N Paris',
    originalPrice: 160000,
    salePrice: 145000,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=1400&q=85',
    itineraryPdf: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    overview: 'The ultimate European grand tour. From the snow-capped Swiss Alps to the romantic canals of Venice and the lights of Paris.',
    highlights: ['Mt. Titlis Excursion', 'Venice Gondola Ride', 'Colosseum in Rome', 'Eiffel Tower'],
    inclusions: ['9 nights stay', 'Breakfast', 'Eurail Global Pass', 'Sightseeing as per itinerary'],
    exclusions: ['Flights', 'Schengen Visa', 'City taxes', 'Meals'],
    itinerary: [
      { day: 1, title: 'Arrival in Zurich / Lucerne', description: 'Arrive in Switzerland, transfer to Lucerne.', activities: ['Check-in', 'Lake Lucerne'] },
      { day: 2, title: 'Mt. Titlis Excursion', description: 'Rotair cable car to Mt. Titlis. Snow activities.', activities: ['Mt. Titlis', 'Ice Flyer'] },
      { day: 3, title: 'Lucerne to Venice', description: 'Scenic train ride through the Alps to Venice, Italy.', activities: ['Scenic Train', 'Gondola Ride'] },
      { day: 4, title: 'Venice to Rome', description: 'Train to Rome. Evening explore the Trevi Fountain.', activities: ['Train Ride', 'Trevi Fountain'] },
      { day: 5, title: 'Rome City Tour', description: 'Visit the Colosseum, Roman Forum, and Vatican City.', activities: ['Colosseum', 'Vatican'] },
      { day: 6, title: 'Rome to Paris', description: 'Fly or take a high-speed train to Paris.', activities: ['Transfer', 'Check-in Paris'] },
      { day: 7, title: 'Paris Highlights', description: 'Eiffel Tower, Seine Cruise, and Louvre Museum.', activities: ['Eiffel Tower', 'Louvre'] },
      { day: 8, title: 'Paris Leisure', description: 'Shopping day at Galeries Lafayette or relax at a cafe.', activities: ['Shopping', 'Leisure'] },
      { day: 9, title: 'Departure', description: 'Transfer to CDG airport for your flight home.', activities: ['Checkout', 'Departure'] }
    ]
  },
  {
    id: 'kudos-kenya',
    destination: 'Kudos Kenya',
    badge: 'Wild Safari',
    badgeColor: '#e8520a',
    category: 'group',
    duration: '6 Days & 5 Nights',
    title: 'Kudos Kenya',
    subtitle: 'The Great Safari Experience',
    hotels: '1N Nairobi · 2N Maasai Mara · 1N Lake Nakuru · 1N Naivasha',
    originalPrice: 85000,
    salePrice: 76999,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1400&q=85',
    itineraryPdf: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    overview: 'Witness the greatest wildlife spectacle on earth. Explore the vast plains of the Maasai Mara, spot the Big Five, and marvel at the flamingos of Lake Nakuru.',
    highlights: ['Maasai Mara Game Drives', 'The Big Five', 'Lake Nakuru Flamingos', 'Boat ride in Lake Naivasha'],
    inclusions: ['5 nights accommodation', 'Full board meals on safari', '4x4 Safari Land Cruiser', 'Park entrance fees'],
    exclusions: ['International Flights', 'Kenya Visa', 'Tips & Gratuities', 'Optional hot air balloon ride'],
    itinerary: [
      { day: 1, title: 'Nairobi Arrival', description: 'Arrive at Jomo Kenyatta International Airport. Transfer to hotel.', activities: ['Check-in', 'Rest'] },
      { day: 2, title: 'Nairobi to Maasai Mara', description: 'Drive to the famous Maasai Mara. Afternoon game drive.', activities: ['Scenic Drive', 'Game Drive'] },
      { day: 3, title: 'Maasai Mara Full Day', description: 'Full day of game viewing. Spot lions, elephants, leopards, and more.', activities: ['Morning Game Drive', 'Picnic Lunch', 'Evening Drive'] },
      { day: 4, title: 'Maasai Mara to Lake Nakuru', description: 'Drive to Lake Nakuru National Park. Afternoon game drive to see rhinos and flamingos.', activities: ['Bird Watching', 'Rhino Sanctuary'] },
      { day: 5, title: 'Lake Nakuru to Naivasha', description: 'Drive to Lake Naivasha. Enjoy a relaxing boat ride to see hippos.', activities: ['Boat Safari', 'Crescent Island Walk'] },
      { day: 6, title: 'Departure', description: 'Drive back to Nairobi for your onward flight.', activities: ['Checkout', 'Departure'] }
    ]
  }
];
